apiVersion: v1
kind: Service
metadata:
    name: "atomaks-bbff"
    labels:
        app: "atomaks-bbff"
spec:
    type: LoadBalancer
    ports:
    - port: 9003
      targetPort: 9003
      protocol: TCP
      name: http
    selector:
        app: "atomaks-bbff"