apiVersion: v1
kind: Service
metadata:
    name: "atomaks-4d9f"
    labels:
        app: "atomaks-4d9f"
spec:
    type: LoadBalancer
    ports:
    - port: 9001
      targetPort: 9001
      protocol: TCP
      name: http
    selector:
        app: "atomaks-4d9f"